### ISSUE TITLE
docs: wrong module name in require?

### ISSUE THREAD

**Issue by zypA13510** [SAP/ui5-simple-require#3]
While reading the docs, I found multiple names are being used as the module name:
1. The module itself is named `ui5-simple-require`
2. And here it is named `ui5-module-loader`:
    > When running the import code:
    > ```javascript
    > const ui5require = require('ui5-module-loader').ui5require;
    > ```

I'm not sure if any of these are typo or leftovers from a refactoring/renaming, and I believe it's better to be consistent.

Could you please verify that all these refer to the same thing?

**Comment by nathanss** [comment]
@zypA13510 

You are right. These are typos from leftovers. I will check and correct.

**Comment by nathanss** [comment]
@zypA13510 I corrected the inconsistencies in the documentation! Thank you for your contribution
